djangocrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('sites.urls'))
]

sites/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, handler404, handler500

app_name = "sites"

urlpatterns = [
    path('', views.home , name="home"),
    path('edit/', views.edit, name="edit"),
    path('result/', views.result, name="result"),
    path("detail/<int:pk>", views.detail ,name="detail"),
    path('delete/<int:pk>', views.delete, name="delete"),
    path('graph/<int:pk>', views.graph, name="graph"),
    path('login/', views.loginView, name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('predict/', views.predict, name="predict"),
    path('predict123/', views.predict_chances, name='submit_prediction'),
    path('predresults/', views.view_results, name='predresults'),
    path('product/', views.product, name="product"),
    path('update/<int:pk>/<int:num>', views.update_a, name="update_a"),
    path('update/<int:pk>/', views.update, name="update"),
]



#
# # error handler 생성
# handler404 = 'sites.views.page_not_found'

sites/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Omo(models.Model):
    battery =models.IntegerField(null=True, default=0)
    bat_status = models.CharField(max_length=10, null=True, default="on")
    r_led = models.IntegerField(null=True, default=0)
    g_led = models.IntegerField(null=True, default=0)
    b_led = models.IntegerField(null=True, default=0)
    r_rpm = models.IntegerField(null=True, default=0)
    l_rpm = models.IntegerField(null=True, default=0)
    buzzer =models.CharField(max_length=10,null=True, default="off")
    headlight = models.CharField(max_length=10,null=True, default="off")
    content = models.TextField(null=True, default="")
    created_at =models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=30, null=True, default="")
    writer =models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
     
    
    def __str__(self):
        return f'{self.pk}'

class PredResults(models.Model):
    battery = models.IntegerField(null=True)
    rpm = models.IntegerField(null=True)
    headlight = models.IntegerField(null=True)
    buzzer = models.IntegerField(null=True)
    led = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f'[{self.pk}]{self.led}'









        

    

    

sites/views.py
from django.shortcuts import render, redirect
from .models import Omo, PredResults
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.contrib.auth.models import User
import pandas as pd
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt


def home(request):
    values = Omo.objects.all().order_by('-pk')

    return render(
        request,
        'sites/home.html',
        {
            'values': values
        }
    )


def predict(request):
    return render(request, 'sites/predict.html')


def predresults(request):
    values = Omo.objects.all().order_by('-pk')

    return render(
        request,
        'sites/predresults.html',
        {
            'values': values
        }
    )


def product(request):
    values = Omo.objects.all().order_by('-pk')

    return render(
        request,
        'sites/product.html',
        {
            'values': values
        }
    )


def loginView(request):
    if request.method == "POST":
        username = request.POST.get('user_id')
        password = request.POST.get('user_pw')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user=user)
            return redirect('/home')

        else:
            return render(request, 'sites/login.html')
    else:
        return render(request, 'sites/login.html')


def logoutView(request):
    auth.logout(request)
    return redirect('/home')


def detail(request, pk):
    pk_num = Omo.objects.get(id=pk)

    context = {
        'detail': pk_num,
        'update': pk_num,
        'graph': pk_num,

    }
    return render(request, 'sites/detail.html', context)


def graph(request, pk):
    pk_num = Omo.objects.get(id=pk)

    context = {
        'graph': pk_num
    }
    return render(request, "sites/graph.html", context)


def result(request):
    if request.method == "POST":
        data = Omo()
        data.battery = request.POST.get("battery")
        data.bat_status = request.POST.get("bat_status")
        data.buzzer = request.POST.get("buzzer")
        data.r_led = request.POST.get("r_led")
        data.g_led = request.POST.get("g_led")
        data.b_led = request.POST.get("b_led")
        data.r_rpm = request.POST.get("r_rpm")
        data.l_rpm = request.POST.get("l_rpm")
        data.headlight = request.POST.get("headlight")
        data.content = request.POST.get("content")
        data.writer = request.user
        data.save()
        print("DB 입력 완료")
        values = Omo.objects.all().order_by('-pk')
        return redirect("/home/result/")  # render(request, 'sites/result.html')
        # 입력을 마치면  POST요청을 주면 바로

    values = Omo.objects.all().order_by('-pk')

    context = {
        'values': values,
    }

    return render(request, 'sites/result.html', context)


def edit(request):
    if request.method == "POST":
        data = Omo()
        data.battery = request.POST.get("battery")
        data.buzzer = request.POST.get("buzzer")
        data.r_led = request.POST.get("r_led")
        data.g_led = request.POST.get("g_led")
        data.b_led = request.POST.get("b_led")
        data.r_rpm = request.POST.get("r_rpm")
        data.l_rpm = request.POST.get("l_rpm")
        data.headlight = request.POST.get("headlight")
        data.content = request.POST.get("content")
        data.writer = request.user
        data.save()
        print("DB 입력 완료")
        print(request.user)
        return redirect("/home/result/")
        # render(request, 'sites/result.html')
        # 입력을 마치면  POST요청을 주면 바로

    else:
        return render(request, 'sites/edit.html')


def delete(request, pk):
    pk_num = Omo.objects.get(id=pk)
    pk_num.delete()

    return redirect("/home/result/")


#
# # error 랜더링
# def page_not_found(request, exception):
#     return render(request, 'common/404.html', {})
def predict_chances(request):
    if request.POST.get('action') == 'post':
        # Receive data from client
        battery = float(request.POST.get('battery'))
        rpm = float(request.POST.get('rpm'))
        headlight = float(request.POST.get('headlight'))
        buzzer = float(request.POST.get('buzzer'))

        # Unpickle model
        # 경로 맞는지 재확인 필요
        model = pd.read_pickle(r'PredResults_model.pickle')
        # Make predictionredResults_model.pickle'
        result = model.predict([[battery, rpm, headlight, buzzer]])

        led = result[0]
        PredResults.objects.create(battery=battery, rpm=rpm, headlight=headlight, buzzer=buzzer, led=led)
        return JsonResponse({'result': led, 'battery': battery,
                             'rpm': rpm, 'headlight': headlight, 'buzzer': buzzer},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "sites/predresults.html", data)


def update(request,pk):
    pk_num=Omo.objects.get(id=pk)
    context={
        'update':pk_num,
        
    }
    return render(request,"sites/update.html",context)

@csrf_exempt
def update_a(request,pk,num):
    print(pk)
    print(num)
    pk_num=Omo.objects.get(id=pk)

    if request.method =="POST":
        if num==1:
            print("ajax요청")
            json_data=json.loads(request.body)
            print("json_data:",json_data["battery"])
            print(pk_num.battery)
            pk_num.battery=json_data["battery"]
            print(pk_num.battery)
            pk_num.save()
            
        # pk_num.r_led=request.POST.get("r_led")
        # pk_num.g_led=request.POST.get("g_led")
        # pk_num.b_led=request.POST.get("b_led")
        # pk_num.r_rpm=request.POST.get("r_rpm")
        # pk_num.l_rpm=request.POST.get("l_rpm")
            context={
                'battery': json_data['battery'],

            }
            print("DB저장 완료")
            return JsonResponse(context)
        
        elif num==2:
            print("ajax요청")
            json_data=json.loads(request.body)
            print("json_data:",json_data)
            pk_num.r_led= json_data['r_led']
            pk_num.g_led = json_data['g_led']
            pk_num.b_led = json_data['b_led']
            pk_num.save()
            context={
                'r_led': json_data["r_led"],
                'g_led': json_data["g_led"],
                'b_led': json_data["b_led"],

            }
            print("DB저장 완료")
            return JsonResponse(context)
        
        elif num==3:
            print("ajax요청")
            json_data=json.loads(request.body)
            print("json_data:",json_data)
            pk_num.r_rpm= json_data['r_rpm']
            pk_num.l_rpm = json_data['l_rpm']
            pk_num.save()
            context={
                'r_rpm': json_data["r_rpm"],
                'l_rpm': json_data["l_rpm"],
            }
            print("DB저장 완료")
            return JsonResponse(context)

sites/templates/sites/about.html
<!DOCTYPE html>
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <link rel="stylesheet" href="{% static 'sites/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'sites/bootstrap/bootstrap.min.css' %}" media="screen">



</head>
<body>
<!-- 헤더 들어갈 자리 -->
{% include 'sites/header.html' %}



<!--어바웃 우리의 소개 들어갈 자리 -->


<!--푸터 들어갈 자리-->
{% include 'sites/footer.html' %}
</body>

</html>

sites/templates/sites/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>

    <link rel="stylesheet" href="{% static 'sites/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/header.css' %}">



</head>
<body>

    <table
            border="1"
            width="50%"
            height="200"
            cellspacing="5">
            <caption><h3>Omo robot Info</h3></caption>
            <thead>
                <tr align="center" bgcolor="white">
                    <th>번호</th>
                    <th>작성자</th>
                    <th>배터리 잔량</th>
                    <th>부저</th>
                    <th colspan="3">LED 정보</th>
                    <th>만든일자</th>
                </tr>
            </thead>

            <tbody>


                <tr align="center" bgcolor="white">
                    <td>{{detail.pk}}</td>
                    <td>{{detail.author}}님</td>
                    <td>{{detail.battery}}% </td>
                    <td>{{detail.buzzer}} </td>
                    <td>R: {{ detail.r_led }}</td>
                    <td>G: {{ detail.g_led }}</td>
                    <td>B: {{ detail.b_led }}</td>
                    <td>{{detail.created_at}}</td>
                </tr>

                    <button type="button"><a href="{% url 'update' update.pk %}">update 하기</a></button>
                    <button type="button"><a href="{% url 'graph' graph.pk %}">graph 하기</a></button>

               <!-- <a href="{% url 'detail' detail.pk %}">update 하기</a> -->

               <button><a href="{% url 'result'%}">상세 목록</a></button>


            </tbody>
        </table>

</html>

sites/templates/sites/edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>

<!--    부트 스트랩 cdn -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="//cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/css/bootstrap4-toggle.min.css" rel="stylesheet">

<!--    css static 파일 -->
    <link rel="stylesheet" href="{% static 'sites/css/edit.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/header.css' %}">
</head>

<body style="background-color:#d9d7d8;">
<!-- 헤더 -->
{% include 'sites/header.html' %}

<section style="margin-bottom: 120px;">
  <div class="form-box">
      <h1> 동력 제어기 </h1>
      <p> 제어값을 입력하세요. </p>
      </br></br>

      <!-- 폼 입력시작 -->
      <form method="post">

          {% csrf_token %}

          <!-- led 색상 표시  -->
            <div class="form-group">
              <label> LED 색상 </label>
                <div class="input-group flex-nowrap">
                  <span class="input-group-text" style="font-size: small; background-color: #ff8282;" id="r_led"> R </span>
                  <input type="text" class="form-control" name="r_led" placeholder="Red"
                         aria-label="ledColor" aria-describedby="r_led" required>
                  <span class="input-group-text" style="font-size: small; background-color:rgb(147, 218, 147);" id="g_led"> G </span>
                  <input type="text" class="form-control" name="g_led" placeholder="Green"
                         aria-label="ledColor" aria-describedby="g_led" required>
                  <span class="input-group-text" style="font-size: small; background-color: rgb(131, 170, 255);" id="b_led"> B </span>
                  <input type="text" class="form-control" name="b_led" placeholder="Blue"
                         aria-label="ledColor" aria-describedby="b_led" required>
                </div>
            </div><br>

            <!-- 바퀴 rpm 표시 -->
            <div class="form-group">
              <label for="r_rpm"> 바퀴 RPM </label>
                <div class="input-group flex-nowrap">
                  <span class="input-group-text" id="l_rpm" style="font-size: small;">L</span>
                  <input type="text" class="form-control" name="l_rpm" placeholder=" "
                         aria-label="rpmLeft" aria-describedby="l_rpm" required>
                  <span class="input-group-text" id="r_rpm" style="font-size: small;">R</span>
                  <input type="text" class="form-control" name="r_rpm"placeholder=" "
                         aria-label="rpmRight" aria-describedby="r_rpm" required>
                </div>
            </div><br>

            <!-- battery-->
            <div class="form-group">
              <label for="battery"> 배터리 </label>
                <div class="input-group flex-nowrap">
                  <span class="input-group-text" id="battery" style="font-size: small;">battery</span>
                  <input type="text" class="form-control" name="battery" placeholder=""
                         aria-label="battery" aria-describedby="battery" required>
                </div>
            </div><br>

            <!-- 부저 on/off -->
            <div class="form-group">
                <label for="buzzer"style="margin-right:133px"> 버저 </label>
                <input type="checkbox" name="buzzer" id="buzzer" class="edit_onoff"
                     checked data-toggle="toggle" data-style="ios" data-size="mini">
            </div>

              <!-- 헤드라이트 on/off -->
            <div class="form-group">
                <label for="headlight"style="margin-right:83px"> 헤드라이트 </label>
              <input type="checkbox" name="headlight" id="headlight"
                     checked data-toggle="toggle" data-style="ios" data-size="mini" >
            </div><br>

              <!-- 동력 제어 참고사항 기재 -->
            <div class="form-group">
              <label for="content"> 동력 제어 참고사항 </label>
              <textarea class="form-control" id="content" name="content"></textarea>
            </div><br>
            <div>
        <!-- 입력 제출 버튼 -->
           <input class="btn btn-outline-secondary"
                  type="submit" value="입력">
            </div><br>
      </form>
  </div>
</section>



<!--푸터 들어갈 자리-->
{% include 'sites/footer.html' %}


<!-- 제이쿼리 스크립트 코드-->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/js/bootstrap4-toggle.min.js"></script>

</body>
</html>

sites/templates/sites/footer.html
        <!-- Footer-->
        <footer class="mt-2 py-1 bg-light fixed-bottom" style="">
            <div class="container" >
                <div class="row mb-3">
                    <div class="col text-center" style="flex-grow: 1 !important;" >
                        <p class="mb-3" style="color: rgb(177, 177, 177); margin-top: 25px; "> Copyright. Ecuzo  </p>
                    </div>
                  </div>
            </div>
        </footer>

sites/templates/sites/home.html
<!DOCTYPE html>
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>


    <link rel="stylesheet" href="{% static 'sites/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'sites/bootstrap/bootstrap.min.css' %}" media="screen">



</head>

<body>
<!-- 헤더 들어갈 자리 -->
{% include 'sites/header.html' %}

<!-- 로그인 창 -->
<!--로그인에 성공했을 경우-->
<div>
{% if user.is_authenticated %}
    <div style="height: auto; width: 50%; margin-top: 100px; float: right; position: relative;">
        <div style="position: absolute; top: 20%; font-size: 40px; color: gray; text-align:center;">
            Welcome <br> Hope you have good </p><span><h1 class="text"></h1></span>
        </div>

        <form>
            <div class="col-7 mx-auto" style="left: -25%; right: 20%; float: right; margin: 300px 300px 200px 200px;">
                <input class="btn btn-outline-secondary btn-lg" id="submitbtn"
                       style="position:absolute; top:60px; color: white; border-color: white; border-width: 1.5px; border-style:solid; border-radius:0px;"
                       type="button" value="Logout" onclick=location.href="{% url 'sites:logout' %}">
            </div>
        </form>
    </div>

    {% else %}


    <div style="height: auto; width: 50%; margin-top: 80px; float: right; position: relative;">
        <div class="getready" style="position: absolute; top: 20%; left:12%; font-size: 40px; color: gray; text-align:center;">
            Get ready <br> to </p><span><h1 class="text"></h1></span>
        </div>
    <!--로그인 하지 않았을 경우 로그인 창 활성화     -->
     {% if user.is_anonymous %}
        <form>
            <div class="col-7 mx-auto" style="left: -25%; right: 20%; float: right; margin: 400px 300px 200px 200px;">
                <input class="btn btn-outline-secondary btn-lg" id="submitbtn"
                       style="color: white; border-color: white; border-width: 1.5px; border-style:solid; border-radius:0px;"
                       type="button" value="Login" onclick=location.href="{% url 'sites:login' %}">
            </div>
        </form>
    </div>
    {% endif%}
  {% endif%}


</div>





<!--푸터 들어갈 자리-->
{% include 'sites/footer.html' %}
<script src="{% static 'sites/js/home.js'%}"></script>

</body>

</html>

sites/templates/sites/predict.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Predict</title>

    <!--css 적용링크 -->
    <link rel="stylesheet" href="{% static 'sites/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/edit.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'sites/css/predict.css' %}">

<!--    부트스크랩 링크 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="//cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'sites/bootstrap/bootstrap.min.css' %}" media="screen">


</head>
<body style="background-color:#d9d7d8;">
<!-- 헤더 들어갈 자리 -->
{% include 'sites/header.html' %}

<section>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> Led 예측 </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

<!--            예측 결과 모달-->
            <div class="modal-body">
                <h5>Led 예측:</h5>
                <div>battery: <span id="sl"></span></div>
                <div>rpm: <span id="sw"></span></div>
                <div>headlight: <span id="pl"></span></div>
                <div>buzzer: <span id="pw"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id ="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-secondary" href="../predresults" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>


<!--예측 바디 입력값-->
<section style="margin-bottom:80px;">
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Led 예측</h1>
            <br>
            <form id="post-form">
                {% csrf_token %}

<!--                배터리 입력 -->
                <div class="form-group">
                    <label for="battery">Battery</label>
                    <input name="battery" type="number" step="0.1" class="form-control" id="battery" required>
                </div>

<!--                RGB 입력 -->
                <div class="form-group">
                    <label for="rpm">Rpm</label>
                    <input name="rpm" type="number" step="0.1" class="form-control" id="rpm" required>
                </div>

                <div class="form-group">
                    <label for="headlight">Headlight(off=0, on=1)</label>
                    <input name="headlight" type="number" step="0.1" class="form-control" id="headlight" required>
                </div>
                <div class="form-group">
                    <label for="buzzer">Buzzer(off=0, on=1)</label>
                    <input name="buzzer" type="number" step="0.1" class="form-control" id="buzzer" placeholder="" required>
                </div>
                <br>
<!--                제출 버튼 -->
                <div style=" text-align: center;">
                    <button type="submit" value="Submit" class="btn btn-outline-secondary"
                        data-toggle="modal" data-target="#exampleModal" style=" display: inline-block;"> 예측 </button>
                 </div>

            </form>


        </div>
    </div>
</div>
</section>
</section>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "sites:submit_prediction" %}',
            data:{
                battery:$('#battery').val(),
                rpm:$('#rpm').val(),
                headlight:$('#headlight').val(),
                buzzer:$('#buzzer').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['battery']
                document.getElementById("sw").innerHTML = json['rpm']
                document.getElementById("pl").innerHTML = json['headlight']
                document.getElementById("pw").innerHTML = json['buzzer']
            },
            error : function(xhr,errmsg,err) {
            }
        });
    })




</script>

<!--푸터 들어갈 자리-->
{% include 'sites/footer.html' %}

<!--제이쿼리, ajax 스크립트 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/js/bootstrap4-toggle.min.js"></script>

</body>
</html>